image: gitpod/workspace-full
tasks:
  - init: >
      cp config.toml.example config.toml && 
      ./x.py build && ./x.py install && 
      ./x.py install cargo &&
      ./build/bootstrap/debug/cargo test
